miniblog/miniblog/urls.py
from django.contrib import admin
from django.urls import path
from blog import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('aboutus/', views.aboutus, name='aboutus'),
    path('contact/', views.contact, name='contact'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('signup/', views.signup, name='signup'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('addpost/', views.Add_Post, name='addpost'),
    path('updatepost/<int:id>/', views.Update_Post, name='updatepost'),
    path('deletepost/<int:id>/', views.Delete_Post, name='deletepost')
]

miniblog/blog/models.py
from django.db import models


# Create your models here.
class Post(models.Model):
    title=models.CharField(max_length=150)
    desc=models.TextField()

class Contact(models.Model):
    name=models.CharField(max_length=150)
    email=models.EmailField()
    address=models.CharField(max_length=500)
    message=models.TextField()

miniblog/blog/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm,UsernameField
from django.contrib.auth.models import User
from django.utils.translation import gettext, gettext_lazy as _
from .models import Post, Contact

class SignUpForm(UserCreationForm):
    password1 = forms.CharField(label='Password', label_suffix=" ",widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password2 = forms.CharField(label='Confirm Password(again)', label_suffix=" ",widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    class Meta:
        model=User
        fields=['username','first_name', 'last_name', 'email']
        labels={'first_name':'First Name', 'last_name':'Last Name', 'email':'Email'}
        widgets={'username':forms.TextInput(attrs={'class':'form-control'}),
                 'first_name': forms.TextInput(attrs={'class': 'form-control'}),
                 'last_name': forms.TextInput(attrs={'class': 'form-control'}),
                 'email': forms.EmailInput(attrs={'class': 'form-control'}) }


class LoginForm(AuthenticationForm):
    username =UsernameField(widget=forms.TextInput(attrs={'autofocus':True, 'class':'form-control'}))
    password = forms.CharField(label=_("Password"), strip=False, widget=forms.PasswordInput(attrs={'autocomplete':'current-password','class':'form-control'}))

class PostForm(forms.ModelForm):
    class Meta:
        model=Post
        fields=['title', 'desc']
        labels={'title':'Titlte', 'desc':'description'}
        widgets={'title':forms.TextInput(attrs={'class':'form-control'}),
                 'desc':forms.Textarea(attrs={'class':'form-control'}),}

class ContactForm(forms.ModelForm):
    class Meta:
        model=Contact
        fields=['name','email', 'address', 'message']
        labels = {'name': 'Name', 'Email': 'Email', 'address':'Address', 'message':'Message'}
        widgets = {'name': forms.TextInput(attrs={'class': 'form-control'}),
                   'email': forms.EmailInput(attrs={'class': 'form-control'}),
                   'address': forms.TextInput(attrs={'class': 'form-control'}),
                   'message': forms.Textarea(attrs={'class': 'form-control'}), }

miniblog/blog/views.py
from django.shortcuts import render, HttpResponseRedirect
from .forms import SignUpForm, LoginForm, PostForm, ContactForm
from django.contrib.auth import login,authenticate,logout
from django.contrib import  messages
from blog.models import Post
from django.contrib.auth.models import Group

# Create your views here.
def home(request):
    posts=Post.objects.all()
    return render(request, 'blog/home.html',{'posts':posts})

def aboutus(request):
    return render(request, 'blog/aboutus.html')

def contact(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            form=ContactForm(request.POST)
            if form.is_valid():
                form.save()
                messages.success(request,'Your message has been sent Successfully!!!')
                form=ContactForm()
        else:
            form=ContactForm()
        return render(request, 'blog/contact.html',{'form':form})
    else:
        return HttpResponseRedirect('/login/')



def dashboard(request):
    if request.user.is_authenticated:
        posts = Post.objects.all()
        user=request.user
        full_name=user.get_full_name()
        gps=user.groups.all()
        return render(request, 'blog/dashboard.html',{'posts':posts,'full_name':full_name, 'groups':gps})
    else:
        return HttpResponseRedirect('/login/')


def user_logout(request):
    logout(request)
    return HttpResponseRedirect('/')


def signup(request):
    if request.method == "POST":
        fm=SignUpForm(request.POST)
        if fm.is_valid():
            messages.success(request, 'Congratulations you have become an Author !!!!')
            user=fm.save()
            group=Group.objects.get(name='Author')
            user.groups.add(group)

            # un=fm.cleaned_data.get('username')
            # fn=fm.cleaned_data['first_name']
            # ls=fm.cleaned_data['last_name']
            # em=fm.cleaned_data['email']
            # user=authenticate(username=un,first_name=fn,last_name=ls,email=em)
            # login(request, user)
            # return HttpResponseRedirect('/')
            fm = SignUpForm()

    else:
        fm=SignUpForm()
    return render(request, 'blog/signup.html', {'form':fm})

def user_login(request):
    if not request.user.is_authenticated:
        if request.method =="POST":
            form=LoginForm(request=request, data=request.POST)
            if form.is_valid():
                uname=form.cleaned_data['username']
                pwd=form.cleaned_data.get('password')
                user=authenticate(username=uname, password=pwd)
                if user is not None:
                    login(request,user)
                    messages.success(request,'Logged in successfully!!!')
                    return HttpResponseRedirect('/dashboard/')
        else:
                form=LoginForm()
        return render(request, 'blog/login.html', {'form':form})

    else:
        return HttpResponseRedirect('/dashboard/')


#Add new Post
def Add_Post(request):
    if request.user.is_authenticated:
        if request.method == "POST":
            form=PostForm(request.POST)
            if form.is_valid():
                title=form.cleaned_data['title']
                desc=form.cleaned_data['desc']
                pst=Post(title=title,desc=desc)
                pst.save()
                form=PostForm()
        else:
            form=PostForm()
        return render(request, 'blog/add_post.html',{'form':form})
    else:
        return HttpResponseRedirect('/login/')

#update Post
def Update_Post(request, id):
    if request.user.is_authenticated:
        if request.method == "POST":
            pi=Post.objects.get(pk=id)
            form=PostForm(request.POST, instance=pi)
            if form.is_valid():
                form.save()
                messages.success(request,'Blog Updated Successfully!!!')
                form=PostForm()
        else:
            pi=Post.objects.get(pk=id)
            form=PostForm(instance=pi)
        return render(request, 'blog/update_post.html',{'form':form})
    else:
          return HttpResponseRedirect('/login/')

def Delete_Post(request, id):
    if request.user.is_authenticated:
        if request.method == "POST":
            pi=Post.objects.get(pk=id)
            pi.delete()
            return HttpResponseRedirect('/dashboard/')
    else:
        return HttpResponseRedirect('/login/')

miniblog/blog/templates/blog/aboutus.html
{% extends 'blog/base.html' %}
{% load static %}
{% block content %}
<div class="col-sm-10">
    <h3 class ="my-5">About Page</h3>

    <p>A blog can be utilized as a platform to showcase your knowledge and expertise.
        Publishing blog posts that are accurate, timely, relevant, and informative will eventually
        get the attention of industry insiders and earn you recognition as an authoritative source and
        thought-leader.</p>
    <p>Blogging is a great way for aspiring authors and freelance writers to build up an online portfolio.
        By showcasing their writing skills on large platforms with expansive reach, freelancers can grow
        their exposure and sign new clients.</p>
</div>

{% endblock content %}

miniblog/blog/templates/blog/add_post.html
{% extends 'blog/base.html' %}
{% load static %}
{% block content %}

<div class="col-sm-10">
    <h3 class="text-white my-5">Dashboard ADD POST </h3>

    <form action="" method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" class="btn btn-success" value="Add">
        <a href="{% url 'dashboard' %}" class="btn btn-danger">Cancel</a>

    </form>
</div>
{% endblock content %}

miniblog/blog/templates/blog/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">

<link rel="stylesheet"  href="{% static 'blog/css/bootstrap.css' %}">
<link  rel="stylesheet" href="{% static 'blog/css/style.css' %}">
</head>
<body>
<div class="container-fluid bg-dark">
{% include 'blog/navbar.html' %}
</div>

<div class="container">
    <div class="row">
        <div class="col-sm-12">
            {% block msg %}
            {% endblock msg %}
        </div>
    </div>

    <div class="row">
        {% block side %}

        {% endblock side %}
        {% block content %}
        {% endblock content %}
    </div>
</div>


<script src="{% static 'blog/js/jquery.js' %}"></script>
<script src="{% static 'blog/js/popper.js' %}"></script>
<script src="{% static 'blog/js/bootstrap.js' %}"></script>
</body>
</html>

miniblog/blog/templates/blog/contact.html
{% extends 'blog/base.html' %}
{% load static %}


{% block msg %}
 {% if messages %}
        {% for msg in messages %}
        <div {% if msg.tags %} class="alert alert-{{msg.tags}} my-3" {% endif %}>
            <strong>{{msg}}</strong>
        </div>

        {% endfor %}
        {% endif %}
{% endblock msg %}


{% block content %}
<div class="col-sm-10">
    <h3 class ="my-5">Contact Page</h3>

    <form action="" method="POST">
        {% csrf_token %}
        <p>{{form}}</p>





        <input type="submit" value="submit" class="btn btn-success">
    </form>

<!--<form>-->

<!--    <div class="form-row">-->
<!--        <div class=" form-group col-md-6">-->
<!--            <label for="InputName">Name</label>-->
<!--            <input type="text" class="form-control" id="InputName">-->
<!--        </div>-->
<!--         <div class=" form-group col-md-6">-->
<!--            <label for="InputEmail">Email</label>-->
<!--            <input type="text" class="form-control" id="InputEmail">-->
<!--        </div>-->
<!--    </div>-->
<!--    <div class="form group">-->
<!--         <label for="Address">Address</label>-->
<!--          <input type="text" class="form-control" id="Address">-->
<!--    </div>-->

<!--    <div class="form group">-->
<!--         <label for="message">Message</label>-->
<!--        <textarea class="form-control" id="message" rows="3"></textarea>-->
<!--    </div>-->
<!--    <br>-->
<!--    <button type="submit" class=" btn btn-primary">Send</button>-->

<!--</form>-->

</div>

{% endblock content %}

miniblog/blog/templates/blog/dashboard.html
{% extends 'blog/base.html' %}
{% load static %}

{% block msg %}
    {% if messages %}
    {% for msg in messages %}
    <div {% if msg.tags %}  class="alert alert-{{msg.tags}} alert-dismissible fade show" {% endif %}>
    <strong>{{msg}}</strong>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span></button>

    </div>
    {% endfor %}
    {% endif %}
    {% endblock msg %}

{% block side %}
<div class="col-sm-2  text-white my-5 text-center">
    <h4 class="my-5">Profile</h4>
    <h5>{{full_name}}</h5>
    {% for group in groups %}
    <p>{{group.name}}</p>
    {% endfor %}

</div>
{% endblock side%}




{% block content %}
<div class="col-sm-10">
    <h3 class ="my-5">Dashboard Page</h3>
    <a href="{% url 'addpost' %}" class="btn btn-success">ADD POST</a>
    <h4 class="text-center alert alert-info mt-3">Show Post Information</h4>

    {% if posts %}
    <table class="table table-hover bg-white">
        <thead>
        <tr class="text-center">
            <th class="scope" style="width:2%">ID</th>
            <th class="scope" style="width:28%">TITLE</th>
            <th class="scope" style="width:55%">DESCRIPTION</th>
            <th class="scope" style="width:15%">ACTION</th>
        </tr>
        </thead>
        <tbody>
        {% for post in posts %}
        <tr>
            <th scope="row">{{post.id}}</th>
            <td>{{post.title}}</td>
            <td>{{post.desc}}</td>
            <td class="text-center">
                <a href="{% url 'updatepost' post.id %}" class="btn btn-warning btn-sm">Edit</a>

                {% if perms.blog.delete_post %}
                <form action="{% url 'deletepost' post.id %}" method="POST" class="d-inline">
                    {% csrf_token %}
                    <input type="submit" class="btn btn-danger btn-sm" value="Delete">
                </form>
                {% endif %}
            </td>
        </tr>

        {% endfor %}
        </tbody>


    </table>
{% else %}
    <h4 class="text-center alert alert-warning">NO Records</h4>
    {% endif %}
</div>
{% endblock content %}

miniblog/blog/templates/blog/home.html
{% extends 'blog/base.html' %}
{% load static %}

{% block content %}
<div class="col-sm-10">
    <h3 class ="my-5">Home Page</h3>
    {% for post in posts %}
    <div class="jumbotron jumbotron-fluid jumbo-color">
        <div class="container">
            <h1 class="display-4 font-weight-bold">{{post.title}}</h1>
            <p class="lead">{{post.desc}}</p>
        </div>
    </div>
    {% endfor %}
</div>



{% endblock content %}

miniblog/blog/templates/blog/login.html
{% extends 'blog/base.html' %}
{% load static %}
{% block content %}
<div class="col-sm-10">
    <h3 class ="my-5">Login Page</h3>

<form action="" method="POST" novalidate>
    {% csrf_token %}
    {% for form in form %}
    <div class="form-group">
        {{form.label_tag}} {{form}} <small class="text-warning">{{form.errors|striptags}}</small><br>
    </div>
    {% endfor %}


    {% if form.non_field_errors %}
    {% for error in form.non_field_errors %}
    <p class="alert alert-danger my-3">{{error}}</p>
    {% endfor %}
    {% endif %}


    <input type="submit" value="Login" class="btn btn-primary">




</form>
</div>
{% endblock content %}

miniblog/blog/templates/blog/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Mini Blog</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'aboutus' %}">Aboutus</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'contact' %}">Contact</a>
        </li>
         {% if request.user.is_authenticated %}
           <li class="nav-item">
          <a class="nav-link" href="{% url 'dashboard' %}">Dashboard</a>
        </li>
           <li class="nav-item">
          <a class="nav-link" href="{% url 'logout' %}">Logout</a>
        </li>
        {% else %}
           <li class="nav-item">
          <a class="nav-link" href="{% url 'signup' %}">Signup</a>
        </li>
           <li class="nav-item">
          <a class="nav-link" href="{% url 'login' %}">Login</a>
        </li>
        {% endif %}

      </ul>
    </div>
  </div>
</nav>

miniblog/blog/templates/blog/signup.html
{% extends 'blog/base.html' %}
{% load static %}
{% block content %}
<div class="col-sm-10">
    <h3 class ="my-5">Become an Author</h3>
    <form action="" method="POST" novalidate>
        {% csrf_token %}

         {% if messages %}
        {% for msg in messages %}
        <p {% if msg.tags %} class="alert alert-{{msg.tags}} mb-5" {% endif %}>{{msg}}</p>
        {% endfor %}
        {% endif %}


        {% for fm in form %}
        <div class="form-group">
            {{fm.label_tag}}{{fm}} <small class="text-warning">{{fm.errors|striptags}}</small><br>
        </div>
        {% endfor %}
<!--        if user submit with a blank field then it gives non-field error-->
        {% if form.non_field_errors %}
        {% for error in form.non_field_errors %}
        <p class="alert alert-danger my-3">{{error}}</p>
        {% endfor %}
        {% endif %}
        <input type="submit" value="Submit" class="btn btn-primary">


    </form>
   
</div>
{% endblock content %}

miniblog/blog/templates/blog/update_post.html
{% extends 'blog/base.html' %}
{% load static %}

{% block msg %}

 {% if messages %}
         {% for message in messages %}
         <div {% if message.tags %} class="alert alert-{{message.tags}} alert-dismissible fade-show my-3" {% endif %}>
             <strong>{{message}}</strong>
         </div>
         {% endfor  %}
         {% endif %}
{% endblock msg %}

{% block content %}
<div class="col-sm-10">
    <h3 class="text-white my-5">Dashboard Update POST </h3>
     <form action="" method="POST">
        {% csrf_token %}
        {{form.as_p}}

        <input type="submit" class="btn btn-success" value="Update">
        <a href="{% url 'dashboard' %}" class="btn btn-danger">Cancel</a>

    </form>

</div>
{% endblock content %}